spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persons
    username: root
    password: nisho0610
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
server:
  port:
    9090
